spring.application.name=users


spring.datasource.url=jdbc:mysql://mysql:3306/todo_list?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=xxxxxx
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.type=trace

spring.flyway.baselineOnMigrate=true

#server.port=8081


# Kafka
spring.kafka.bootstrap-servers=kafka:9092

# Producer (User ? Order request)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer (Order ? User response)
spring.kafka.consumer.group-id=users-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.admin.auto-create=false

#  logging ----
logging.level.root=INFO

#logging.level.org.apache.kafka=WARN
#logging.level.org.apache.kafka.clients=WARN
#logging.level.org.apache.kafka.clients.NetworkClient=ERROR
#logging.level.org.apache.kafka.clients.Metadata=ERROR
#logging.level.org.apache.kafka.clients.consumer.internals=ERROR
#logging.level.org.apache.kafka.clients.producer.internals=ERROR
#
#logging.level.org.springframework.kafka=WARN
#
#logging.level.com.todoapp=INFO
#logging.level.com.orders=INFO

management.endpoints.web.exposure.include=health,info
